### ISSUE TITLE
Stateful policy enforce model corner case

### ISSUE THREAD

**Issue by echkenluo** [everoute/everoute#177]

**Comment by KeyongSun** [comment]
@echkenluo  这里指的什么 case？

**Comment by echkenluo** [comment]
在 ER 部署到 ER 白名单下发之间建立的连接（ct state 为 established），若连接建立双方不主动关闭连接或发生连接意外关闭，该连接状态为 established。若白名单中不包含该连接，该连接的数据包应当被丢弃。但是由于 CT state 在 est，会绕过丢弃规则，直通。
