### ISSUE TITLE
Tier0 policy corner case

### ISSUE THREAD

**Issue by echkenluo** [everoute/everoute#199]

**Comment by KeyongSun** [comment]
The isolation policy with highest priority, if a VM configured as isolation, then any other whitelist rule with this VM will not take effect.

Rule <------------> Priority(From high to low)
-----------------------------------------------
Isolation       |           Ingress/Egress Drop
                     |           forensic one side drop [VM2: Allow VM1 access VM2, but not allow VM2 egress traffic]
-----------------------------------------------
forensic       |           WhiteList Accept [[VM2: Allow VM1 access VM2]
                     |           forensic default Drop [VM2: other access VM2 will be dropped]
-----------------------------------------------
security       |           WhiteList Accept
                     |           Default Drop
-----------------------------------------------
Global          |           Accept/Drop

**Comment by KeyongSun** [comment]
@zwtop

**Comment by KeyongSun** [comment]
Controller plane separate the isolation and forensic rule.
