### ISSUE TITLE
data race problem while switch disconnected

### ISSUE THREAD

**Issue by wu-cl** [everoute/everoute#294]
==================
WARNING: DATA RACE
Read at 0x00c000176010 by goroutine 159:
  github.com/everoute/everoute/pkg/agent/datapath.InitializeVDS.func1()
      /home/runner/work/everoute/everoute/pkg/agent/datapath/multiBridgeDatapath.go:435 +0x148

Previous write at 0x00c000176010 by goroutine 245:
  [failed to restore the stack]

Goroutine 159 (running) created at:
  github.com/everoute/everoute/pkg/agent/datapath.InitializeVDS()
      /home/runner/work/everoute/everoute/pkg/agent/datapath/multiBridgeDatapath.go:432 +0x10dd
  github.com/everoute/everoute/pkg/agent/datapath.(*DpManager).InitializeDatapath.func1()
      /home/runner/work/everoute/everoute/pkg/agent/datapath/multiBridgeDatapath.go:266 +0x9b

Goroutine 245 (finished) created at:
  github.com/contiv/ofnet/ofctrl.NewSwitch()
      /root/go/pkg/mod/github.com/everoute/ofnet@v0.0.0-20211209095049-dffbfc664db0/ofctrl/ofSwitch.go:78 +0x4eb
  github.com/contiv/ofnet/ofctrl.(*Controller).handleConnection()
      /root/go/pkg/mod/github.com/everoute/ofnet@v0.0.0-20211209095049-dffbfc664db0/ofctrl/ofctrl.go:254 +0xabd
==================

**Comment by zwtop** [comment]
https://github.com/everoute/everoute/runs/4550988534
